cc_library(
  name="image",
  hdrs=["include/image.hpp"],
  srcs=["src/image.cpp"],
  strip_include_prefix="include",
  include_prefix="tyl/graphics/host",
  deps=["//core/common", "//lib/graphics/device", "@stb//:stb",],
  visibility=["//visibility:public"]
)
