cc_library(
  name="window",
  hdrs=["include/window.hpp"],
  srcs=["src/window.cpp"],
  strip_include_prefix="include",
  include_prefix="tyl/window",
  deps=["@glfw//:glfw", "//lib/graphics/device/glad:glad", ],
  visibility=["//visibility:public"]
)
