cc_library(
  name="app",
  hdrs=["include/app.hpp"],
  srcs=["src/app.cpp"],
  strip_include_prefix="include",
  include_prefix="tyl/engine",
  deps=["//lib/ui", "@imgui//:imgui_cpp", "//lib/logging"],
  visibility=["//visibility:public"]
)

cc_library(
  name="engine",
  hdrs=[],
  srcs=[],
  strip_include_prefix="include",
  include_prefix="tyl/engine",
  deps=[],
  visibility=["//visibility:public"]
)
