cc_library(
  name="common",
  hdrs=glob(["include/*.hpp"]),
  strip_include_prefix="include",
  include_prefix="tyl",
  deps = ["@entt//:entt", "@eigen//:eigen"],
  visibility=["//visibility:public"]
)
