cc_library(
  name="camera",
  hdrs=["include/top_down.hpp"],
  srcs=["src/top_down.cpp"],
  strip_include_prefix="include",
  include_prefix="tyl/camera",
  deps = [
    "//lib/engine/common",
  ],
  visibility=["//visibility:public"]
)
