cc_library(
  name="host",
  hdrs=["include/sound_data.hpp"],
  srcs=["src/sound_data.cpp"],
  strip_include_prefix="include",
  include_prefix="tyl/audio/host",
  deps=["//core/common", "//core/audio/device"],
  visibility=["//visibility:public"]
)
